name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      # Build & Test
      - name: Build and run tests
        run: ./gradlew clean build

      # Detekt
      - name: Run Detekt
        uses: natiginfo/action-detekt-all@v1
        with:
          args: --config detekt-config.yml --input src

      # JaCoCo Report
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true
